/**
 * playlists.mjs — Ryan's predefined radio playlists
 * Add/remove songs here. Leo pulls from these when in playlist mode.
 */

export const PLAYLISTS = {
  'default': [
    { title: 'Blinding Lights', artist: 'The Weeknd' },
    { title: 'Levitating', artist: 'Dua Lipa' },
    { title: 'Stay', artist: 'The Kid LAROI Justin Bieber' },
    { title: 'Peaches', artist: 'Justin Bieber' },
    { title: 'Good 4 U', artist: 'Olivia Rodrigo' },
    { title: 'Montero', artist: 'Lil Nas X' },
    { title: 'Save Your Tears', artist: 'The Weeknd' },
    { title: 'Industry Baby', artist: 'Lil Nas X Jack Harlow' },
    { title: 'Heat Waves', artist: 'Glass Animals' },
    { title: 'As It Was', artist: 'Harry Styles' },
    { title: 'Starboy', artist: 'The Weeknd' },
    { title: 'The Hills', artist: 'The Weeknd' },
    { title: 'Die For You', artist: 'The Weeknd' },
    { title: 'Creepin', artist: 'Metro Boomin The Weeknd' },
    { title: 'Kill Bill', artist: 'SZA' },
    { title: 'Anti-Hero', artist: 'Taylor Swift' },
    { title: 'Flowers', artist: 'Miley Cyrus' },
    { title: 'Cruel Summer', artist: 'Taylor Swift' },
    { title: 'Snooze', artist: 'SZA' },
    { title: 'Vampire', artist: 'Olivia Rodrigo' },
    { title: 'Paint The Town Red', artist: 'Doja Cat' },
    { title: 'Water', artist: 'Tyla' },
    { title: 'Greedy', artist: 'Tate McRae' },
    { title: 'Lovin On Me', artist: 'Jack Harlow' },
    { title: 'Stick Season', artist: 'Noah Kahan' },
  ],
  'late-night': [
    { title: 'Nights', artist: 'Frank Ocean' },
    { title: 'Ivy', artist: 'Frank Ocean' },
    { title: 'Redbone', artist: 'Childish Gambino' },
    { title: 'Lost', artist: 'Frank Ocean' },
    { title: 'Self Control', artist: 'Frank Ocean' },
    { title: 'Pink + White', artist: 'Frank Ocean' },
    { title: 'Solo', artist: 'Frank Ocean' },
    { title: 'Novacane', artist: 'Frank Ocean' },
    { title: 'Swim Good', artist: 'Frank Ocean' },
    { title: 'Chanel', artist: 'Frank Ocean' },
    { title: 'Pyramids', artist: 'Frank Ocean' },
    { title: 'Thinkin Bout You', artist: 'Frank Ocean' },
    { title: 'Super Rich Kids', artist: 'Frank Ocean' },
    { title: 'Sweet Life', artist: 'Frank Ocean' },
    { title: 'Godspeed', artist: 'Frank Ocean' },
    { title: 'White Ferrari', artist: 'Frank Ocean' },
    { title: 'Seigfried', artist: 'Frank Ocean' },
    { title: 'Moon River', artist: 'Frank Ocean' },
    { title: 'Provider', artist: 'Frank Ocean' },
    { title: 'Biking', artist: 'Frank Ocean' },
    { title: 'Lens', artist: 'Frank Ocean' },
    { title: 'In My Room', artist: 'Frank Ocean' },
    { title: 'DHL', artist: 'Frank Ocean' },
    { title: 'Moonlight', artist: 'Kali Uchis' },
    { title: 'Telepatia', artist: 'Kali Uchis' },
  ],
  'hype': [
    { title: 'HUMBLE', artist: 'Kendrick Lamar' },
    { title: 'God Did', artist: 'DJ Khaled'},
    { title: 'Rich Flex', artist: 'Drake 21 Savage' },
    { title: 'Knife Talk', artist: 'Drake' },
    { title: 'Way 2 Sexy', artist: 'Drake' },
    { title: 'SICKO MODE', artist: 'Travis Scott' },
    { title: 'Rockstar', artist: 'Post Malone' },
    { title: 'Congratulations', artist: 'Post Malone' },
    { title: 'Lucid Dreams', artist: 'Juice WRLD' },
    { title: 'Legends Never Die', artist: 'Juice WRLD' },
    { title: 'No Role Modelz', artist: 'J Cole' },
    { title: 'Middle Child', artist: 'J Cole' },
    { title: 'Wet Dreamz', artist: 'J Cole' },
    { title: 'Power Trip', artist: 'J Cole' },
    { title: 'Work Out', artist: 'J Cole' },
    { title: 'The London', artist: 'Young Thug J Cole' },
    { title: 'First Person Shooter', artist: 'Drake J Cole' },
    { title: 'Alright', artist: 'Kendrick Lamar' },
    { title: 'DNA', artist: 'Kendrick Lamar' },
    { title: 'Money Trees', artist: 'Kendrick Lamar' },
    { title: 'Swimming Pools', artist: 'Kendrick Lamar' },
    { title: 'm.A.A.d city', artist: 'Kendrick Lamar' },
    { title: 'N95', artist: 'Kendrick Lamar' },
    { title: 'Rich Spirit', artist: 'Kendrick Lamar' },
    { title: 'family ties', artist: 'Baby Keem Kendrick Lamar' },
  ],
  'chill': [
    { title: 'location', artist: 'Khalid' },
    { title: 'Young Dumb Broke', artist: 'Khalid' },
    { title: 'Talk', artist: 'Khalid' },
    { title: 'Better', artist: 'Khalid' },
    { title: 'Motion', artist: 'Drake' },
    { title: 'Passionfruit', artist: 'Drake' },
    { title: 'Jorja Interlude', artist: 'Drake' },
    { title: 'Get It Together', artist: 'Drake' },
    { title: 'From Time', artist: 'Drake' },
    { title: 'Doing It Wrong', artist: 'Drake' },
    { title: 'Hold On We Are Going Home', artist: 'Drake' },
    { title: 'Marvins Room', artist: 'Drake' },
    { title: 'Take Care', artist: 'Drake' },
    { title: 'Controlla', artist: 'Drake' },
    { title: 'One Dance', artist: 'Drake' },
    { title: 'Blem', artist: 'Drake' },
    { title: 'Signs', artist: 'Drake' },
    { title: 'Fire & Desire', artist: 'Drake' },
    { title: 'Teenage Fever', artist: 'Drake' },
    { title: 'Chicago Freestyle', artist: 'Drake' },
    { title: 'Not You Too', artist: 'Drake' },
    { title: 'Liability', artist: 'Drake' },
    { title: 'Slime You Out', artist: 'Drake SZA' },
    { title: 'Wait For U', artist: 'Future Drake Tems' },
    { title: 'Life Is Good', artist: 'Future Drake' },
  ]
};

export function getPlaylist(name) {
  const key = (name || 'default').toLowerCase();
  return PLAYLISTS[key] || PLAYLISTS['default'];
}

export function getPlaylistNames() {
  return Object.keys(PLAYLISTS);
}
