pub mod reasoner;
pub mod candidates;
pub mod promotion;
pub mod homeostasis;
pub mod lattice;
pub mod inner_voice;
pub mod working_memory;
pub mod compose;
pub mod voice;
pub mod transcript;
pub mod episodic;
pub mod amygdala;
pub mod predictor;
pub mod dmn;
pub mod global_workspace;
pub mod pfc;
pub mod dopamine;
pub mod acc;
pub mod thalamus;
pub mod theory_of_mind;
pub mod insula;
pub mod neuroplasticity;
pub mod sleep;
pub mod cerebellum;
pub mod basal_ganglia;

pub use reasoner::{Reasoner, ContextSlot};
pub use candidates::CandidateBuffer;
pub use promotion::{run_promotion, PromotionThresholds};
pub use homeostasis::{run_homeostasis, HomeostasisConfig};
pub use lattice::{consolidate, observe_dream, reinforce_dream_sources, gate_stats, GateStats};
pub use inner_voice::{validate_insight, explore_lexicon_binding, InsightVerdict};
pub use working_memory::WorkingMemory;
pub use voice::{generate_response, detect_query_type, MoodState};
pub use episodic::{EpisodicStore, EpisodicEvent, compute_salience};
pub use amygdala::{AmygdalaGate, score_emotional_charge};
pub use predictor::PredictiveEngine;
pub use dmn::DefaultModeNetwork;
pub use global_workspace::{GlobalWorkspace, WorkspaceEntry};
pub use pfc::{PrefrontalCortex, PfcVerdict, Goal};
pub use dopamine::DopamineCircuit;
pub use acc::AccMonitor;
pub use thalamus::{ThalamicRelay, ThalamicSignal, RoutedSignal, SignalType};
pub use theory_of_mind::{TheoryOfMind, Familiarity, CommunicationStyle};
pub use insula::{InsulaMonitor, FeltCondition};
pub use neuroplasticity::NeuroplasticityEngine;
pub use sleep::{SleepSystem, SleepReport};
pub use cerebellum::{CerebellumEngine, PrecisionReport};
pub use basal_ganglia::{BasalGanglia, ActionDecision};
